// JSON Sumber = https://data.jakarta.go.id/read-resource/json/tempat-penampungan-sampah-sementara-tps-di-wilayah-dki-jakarta-tahun-2019/331b3c22-3ece-47c0-a8d3-e3f453e9666d
var dataJSON = [
  {
    nama_tps: "Lps Asrama Polisi Rw. 09",
    alamat: "Jl. Cideng Barat",
    kelurahan: "Cideng",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 14,
    status_lahan: "Asrama Polisi",
    "volume_sampah_rata_rata_per_hari(m3)": 1,
  },
  {
    nama_tps: "Dinas teknis",
    alamat: "Jl. Jati baru",
    kelurahan: "Cideng",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 60,
    status_lahan: "Dinas teknis",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Rw.012",
    alamat: "Jl.setia kawan Rt.01",
    kelurahan: "Duri pulo",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 18,
    status_lahan: "PJKA",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Rw.09",
    alamat: "Jl.setia kawan ujung rt 03",
    kelurahan: "Duri pulo",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 20,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Rw.04",
    alamat: "Jl.gambir buntu",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 8,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 1,
  },
  {
    nama_tps: "Perhubungan ",
    alamat: "Jl. Abdul Muis",
    kelurahan: "Gambir ",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 12,
    status_lahan: "Kementerian perhubungan ",
    "volume_sampah_rata_rata_per_hari(m3)": 2,
  },
  {
    nama_tps: "RS. Budi kemuliaan",
    alamat: "Jl. Budi kemuliaan ",
    kelurahan: "Gambir ",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 15,
    status_lahan: "Rs. Budi kemuliaan ",
    "volume_sampah_rata_rata_per_hari(m3)": 1,
  },
  {
    nama_tps: "Rw.07 dan 08",
    alamat: "Jl.binatu 1",
    kelurahan: "Petojo utara",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 24,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Kementrian pertahanan ",
    alamat: "Jl. Tanah Abang timur",
    kelurahan: "Gambir",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 64,
    status_lahan: "Kementerian pertahanan ",
    "volume_sampah_rata_rata_per_hari(m3)": 4,
  },
  {
    nama_tps: "Sekretaris Negara ",
    alamat: "Jl. Medan merdeka Utara ",
    kelurahan: "Gambir ",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 12,
    status_lahan: "Pemerintah ",
    "volume_sampah_rata_rata_per_hari(m3)": 14,
  },
  {
    nama_tps: "Kemenkominfo",
    alamat: "Jl. Abdul muis",
    kelurahan: "Gambir ",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 48,
    status_lahan: "Kemenkominfo",
    "volume_sampah_rata_rata_per_hari(m3)": 2,
  },
  {
    nama_tps: "Pasar Thomas ",
    alamat: "Jl. Tanah Abang V",
    kelurahan: "Petojo selatan ",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 8,
    status_lahan: "Pd pasar jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "LPS gembrong",
    alamat: "Jl.rawa selatan I",
    kelurahan: "Kampung rawa",
    kecamatan: "Johar baru",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 30,
    status_lahan: "Milik Pemda ",
    "volume_sampah_rata_rata_per_hari(m3)": 18,
  },
  {
    nama_tps: "TPS RW. 03 Cikini",
    alamat: "Jl. Raden Saleh II",
    kelurahan: "Cikini",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 20,
    status_lahan: "PU air",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "TPS SMP Negeri 1",
    alamat: "Jl. Cikini raya",
    kelurahan: "Cikini",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 6,
    status_lahan: "Sekolah",
    "volume_sampah_rata_rata_per_hari(m3)": 3,
  },
  {
    nama_tps: "TPS RW. 10 Menteng Tenggulun",
    alamat: "Jl. Menteng Tenggulun",
    kelurahan: "Menteng",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 30,
    status_lahan: "Pinggir kali",
    "volume_sampah_rata_rata_per_hari(m3)": 10,
  },
  {
    nama_tps: "TPS Kimia",
    alamat: "Jl. Kimia",
    kelurahan: "Pegangsaan",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 8,
    status_lahan: "PU Air",
    "volume_sampah_rata_rata_per_hari(m3)": 5,
  },
  {
    nama_tps: "Tps Rusun Benhil II",
    alamat: "Jl. Lan 2 Pejompongan",
    kelurahan: "Bendungan Hilir",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 15,
    status_lahan: "Milik rusun",
    "volume_sampah_rata_rata_per_hari(m3)": 7.5,
  },
  {
    nama_tps: "Tps Rusun Benhil I",
    alamat: "Jl. Penjernihan I",
    kelurahan: "Bendungan Hilir",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 18,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Pasar palmerah",
    alamat: "Jl.Palmerah Selatan",
    kelurahan: "Gelora",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 48,
    status_lahan: "Milik PD Pasar Jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 16,
  },
  {
    nama_tps: "Pasar UKM Lokbin Palmerah",
    alamat: "Jl. Palmerah Barat Rt/Rw 01/02",
    kelurahan: "Gelora",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 18,
    status_lahan: "Milik Pemerintah",
    "volume_sampah_rata_rata_per_hari(m3)": 16,
  },
  {
    nama_tps: "Lps St. Tn Abang",
    alamat: "Jl. Jati Baru",
    kelurahan: "Kampung Bali",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 36,
    status_lahan: "Milik PJKA",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Tps Rusun Karteng",
    alamat: "Jl. Karet Pasar Baru Barat I Rw 07",
    kelurahan: null,
    kecamatan: null,
    wilayah: null,
    jenis_tps: null,
    "luas_lahan(m2)": null,
    status_lahan: null,
    "volume_sampah_rata_rata_per_hari(m3)": null,
  },
  {
    nama_tps: "Tps RSTA Rw 10",
    alamat: "Jl. KH Mas Mansyur",
    kelurahan: "Kebon Kacang",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 10,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Pasar lontar",
    alamat: "Jl.Sabeni Raya ",
    kelurahan: "Kebon melati",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 48,
    status_lahan: "Milik PD Pasar Jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 30,
  },
  {
    nama_tps: "Tps Rusun Petamburan",
    alamat: "Jl. Petamburan V Rw 11",
    kelurahan: "Petamburan",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 6,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 10,
  },
  {
    nama_tps: "Tps Rusun Petamburan",
    alamat: "Jl. Petamburan V Rw 11",
    kelurahan: "Petamburan",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Bak Beton",
    "luas_lahan(m2)": 6,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 10,
  },
  {
    nama_tps: "Dipo rawakerbo",
    alamat: "Jl.Rawasari sel",
    kelurahan: "Cempaka putih timur",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "TPS 3R",
    "luas_lahan(m2)": 150,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 24,
  },
  {
    nama_tps: "Dipo kebon kelapa",
    alamat: "Jl.pintu air 2",
    kelurahan: "Kebon kelapa",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 200,
    status_lahan: "PJKA",
    "volume_sampah_rata_rata_per_hari(m3)": 18,
  },
  {
    nama_tps: "Dipo Tanjung Selor",
    alamat: "Jl. Tanjung selor",
    kelurahan: "Cideng",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 200,
    status_lahan: "Pemda dki",
    "volume_sampah_rata_rata_per_hari(m3)": 40,
  },
  {
    nama_tps: "Dipo Jl. Tanah Abang I",
    alamat: "Jl. Tanah Abang I",
    kelurahan: "Petojo Selatan ",
    kecamatan: "Gambir ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 120,
    status_lahan: "Pemerintah ",
    "volume_sampah_rata_rata_per_hari(m3)": 40,
  },
  {
    nama_tps: "Dipo Johar baru ",
    alamat: "Jl.Johar Baru Utara 1",
    kelurahan: "Johar Baru",
    kecamatan: "Johar Baru",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 225,
    status_lahan: "Milik Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 40,
  },
  {
    nama_tps: "Dipo kota Paris ",
    alamat: "Jl.pulogundul ",
    kelurahan: "Tanah tinggi",
    kecamatan: "Johar baru ",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 180,
    status_lahan: "Milik pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 16,
  },
  {
    nama_tps: "Dipo Kran",
    alamat: "Jl.Kran Raya",
    kelurahan: "Gunung Sahari Selatan",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 225,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 58,
  },
  {
    nama_tps: "Dipo Matraman",
    alamat: "Jl. Matraman Dalam 1",
    kelurahan: "Pegangsaan",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 400,
    status_lahan: "Tanah PU air",
    "volume_sampah_rata_rata_per_hari(m3)": 60,
  },
  {
    nama_tps: "Dipo Gunung Sahari Utara",
    alamat: "Jl. Gunung Sahari 7A",
    kelurahan: "Gunung Sahari Utara",
    kecamatan: "Sawah besar",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 600,
    status_lahan: "PJKA",
    "volume_sampah_rata_rata_per_hari(m3)": 60,
  },
  {
    nama_tps: "Dipo PAM",
    alamat: "Jl. PAM Baru Raya",
    kelurahan: "Bendungan Hilir",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 400,
    status_lahan: "Tanah Milik PU",
    "volume_sampah_rata_rata_per_hari(m3)": 45,
  },
  {
    nama_tps: "Dipo PLN",
    alamat: "Jl. Awaludin IV Rt/Rw 03/17",
    kelurahan: "Kebon Melati",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 264,
    status_lahan: "Tanah Milik PLN",
    "volume_sampah_rata_rata_per_hari(m3)": 30,
  },
  {
    nama_tps: "Dipo Rw 04 Petamburan",
    alamat: "Jl. Petamburan Rw 04",
    kelurahan: "Petamburan",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Dipo",
    "luas_lahan(m2)": 255,
    status_lahan: "Milik Pemerintah",
    "volume_sampah_rata_rata_per_hari(m3)": 20,
  },
  {
    nama_tps: "Kantor DPRD",
    alamat: "Jl.kebon sirih raya ",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Milik pemda DKI ",
    "volume_sampah_rata_rata_per_hari(m3)": 5,
  },
  {
    nama_tps: "Stasiun Gambir",
    alamat: "Jl.medan merdeka timur",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 40,
    status_lahan: "PJKA",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "Lenggang jakarta",
    alamat: "Taman monas",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Lemhanas",
    alamat: "Jl.kebon sirih raya",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 30,
    status_lahan: "Pemerintah pusat",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Kementerian perdagangan",
    alamat: "Jl.ridwan rais",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 21,
    status_lahan: "Pemerintah pusat",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Kantor walikota",
    alamat: "Jl.tanah abang 1",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 24,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 4,
  },
  {
    nama_tps: "Paspampres ",
    alamat: "Jl. Tanah Abang 2",
    kelurahan: "Petojo selatan ",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 16,
    status_lahan: "Paspampres ",
    "volume_sampah_rata_rata_per_hari(m3)": 5,
  },
  {
    nama_tps: "Pasar petojo ilir",
    alamat: "Jl.petojo ilir",
    kelurahan: "Petojo utara",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 16,
    status_lahan: "PD.PASAR",
    "volume_sampah_rata_rata_per_hari(m3)": 14,
  },
  {
    nama_tps: "Pool container Embrio",
    alamat: "Jl.pulo gundul",
    kelurahan: "Tanah tinggi ",
    kecamatan: "Johar baru",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Milik pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Tps Golden",
    alamat: "Jl. Bungur Besar Raya",
    kelurahan: "Gunung Sahari Selatan",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 50,
    status_lahan: "Milik PT. Golden Truly",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "Tps Armabar",
    alamat: "Jl. Bungur Besar Raya",
    kelurahan: "Gunung Sahari Selatan",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 35,
    status_lahan: "Milik Koarmabar",
    "volume_sampah_rata_rata_per_hari(m3)": 12.05,
  },
  {
    nama_tps: "Tps RW. 10 Kebon Kosong",
    alamat: "Jl. Swadaya",
    kelurahan: "Kebon Kosong",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Swadaya warga",
    "volume_sampah_rata_rata_per_hari(m3)": 6.83,
  },
  {
    nama_tps: "Tps Apron",
    alamat: "Jl.Angkasa Raya",
    kelurahan: "Kebon Kosong",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 60,
    status_lahan: "Swadaya warga",
    "volume_sampah_rata_rata_per_hari(m3)": 10,
  },
  {
    nama_tps: "Tips Pasar Kemayoran",
    alamat: "Jl.D ,Utan Panjang",
    kelurahan: "Utan Panjang",
    kecamatan: "Kemayoran",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 360,
    status_lahan: "PD Pasar Jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 9.06,
  },
  {
    nama_tps: "TPS TIM",
    alamat: "Jl. Cikini Raya",
    kelurahan: "Cikini",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 20,
    status_lahan: "Halaman Taman Ismail Marzuki",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "TPS RW. 01 Menteng Tenggulun",
    alamat: "Jl. Menteng Tenggulun",
    kelurahan: "Menteng",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Pinggir Kali",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "TPS RW.01 ",
    alamat: "Jl. Cikini Kramat",
    kelurahan: "Pegangsaan",
    kecamatan: "Menteng",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 15,
    status_lahan: "Jalan Warga",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "Pasar Timbul",
    alamat: "Jl. Gotong Royong",
    kelurahan: "Kartini",
    kecamatan: "Sawah besar",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 20,
    status_lahan: "PD. Pasar",
    "volume_sampah_rata_rata_per_hari(m3)": 18,
  },
  {
    nama_tps: "Istiqlal",
    alamat: "Komplek Masjid Istiqlal",
    kelurahan: "Pasar Baru",
    kecamatan: "Sawah Besar",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 100,
    status_lahan: "Masjid Istiqlal",
    "volume_sampah_rata_rata_per_hari(m3)": 9,
  },
  {
    nama_tps: "lps rw 05 senen",
    alamat: " Jl abdurohman saleh",
    kelurahan: "Senen",
    kecamatan: "Senen",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 16,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 7,
  },
  {
    nama_tps: "Lps pasar kebon jati",
    alamat: "Jl.Kebon Jati",
    kelurahan: "Kampung Bali",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 40,
    status_lahan: "Milik PD Pasar Jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 10,
  },
  {
    nama_tps: "Tps Rw 07 Karteng",
    alamat: "Jl. Karet Pasar Baru Barat I Rw 07",
    kelurahan: "Karet Tengsin",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 42,
    status_lahan: "Milik PU",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Tps RSTA Rw 11",
    alamat: "Jl. Kebon Kacang IX Rw 11",
    kelurahan: "Kebon Kacang",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 25,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Pasar Gandaria",
    alamat: "Jl. Kebon Kacang I",
    kelurahan: "Kebon Kacang",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 30,
    status_lahan: "Milik PD. Pasar Jaya",
    "volume_sampah_rata_rata_per_hari(m3)": 6,
  },
  {
    nama_tps: "Tps RSKK",
    alamat: "Jl. Kb Kacang XI",
    kelurahan: "Kebon Kacang",
    kecamatan: "Tanah Abang",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Container",
    "luas_lahan(m2)": 5,
    status_lahan: "Milik Dinas Perumahan",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Jl.Cempaka putih barat",
    alamat: "jl.cempaka putih barat 2",
    kelurahan: "Cempaka putih barat",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 20,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "Jl.mardani raya",
    alamat: "Jl.mardani raya",
    kelurahan: "Cempaka putih barat",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 16,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 12,
  },
  {
    nama_tps: "jl.cempaka putih timur rw 4",
    alamat: "Jl.cempaka putih timur",
    kelurahan: "Cempaka putih timur",
    kecamatan: "Cempaka Putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 75,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 4,
  },
  {
    nama_tps: "Tps jl.cempaka putih tengah 31",
    alamat: "Jl.cempaka putih tengah 31",
    kelurahan: "Cempaka putih timur",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 30,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 3,
  },
  {
    nama_tps: "Jl.cempaka putih tengah 17",
    alamat: "Jl.cempaka putih tengah 17 rw 7",
    kelurahan: "Cempaka putih timur",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 34,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 9,
  },
  {
    nama_tps: "Jl.percetakan negara IX",
    alamat: "jl.percetakan negara IX",
    kelurahan: "Rawasari",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 20,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Jl.percetakan negara 5",
    alamat: "jl.percetakan negara 5",
    kelurahan: "Rawasari",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 20,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Jl.pramuka jaya sari",
    alamat: "jl.pramuka jaya sari",
    kelurahan: "Rawasari",
    kecamatan: "Cempaka putih",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 14,
    status_lahan: "Pemrov DKI",
    "volume_sampah_rata_rata_per_hari(m3)": 8,
  },
  {
    nama_tps: "Rw.07 dan 08",
    alamat: "Jl.subur baru",
    kelurahan: "Duri pulo",
    kecamatan: "Gambir",
    wilayah: "Jakarta Pusat",
    jenis_tps: "Pool Gerobak",
    "luas_lahan(m2)": 60,
    status_lahan: "Pemda",
    "volume_sampah_rata_rata_per_hari(m3)": 16,
  },
];
